#!/usr/bin/env bash
PROMPT_COMMAND='echo -ne "\033]0;'WDGWV Setup Builder'\007"'
echo -ne "\033]0;'WDGWV Setup Builder'\007"
clear
echo "                   :....................,:,              "
sleep 0.1
echo "                ,.',,,::;;;;;;;;;;;;;;;;:;'              "
sleep 0.1
echo "              '...',::;:::::;;;;;;;;;;;;;::'             "
sleep 0.1
echo "             ,..'',,,::::::::::::::::;:;;:::;            "
sleep 0.1
echo "            :.,,''..::;;,,,,,,,,,,,,,:;;;;;::;'          "
sleep 0.1
echo "           ,.,,,'...,:.:,,,,,,,,,,,,,:;:;;;;:;;          "
sleep 0.1
echo "          '..,,''...;;,;::::::::::::::'';';';:''         "
sleep 0.1
echo "          ,,,,,''..:;,;;:::::::::::::;';;';';;'';        "
sleep 0.1
echo "         ,,,,,''....;,,:::::::;;;;;;;;':'''';''+;        "
sleep 0.1
echo "         :,::'''....,,,:;;;;;;;;;;;;;;;''''';';';;       "
sleep 0.1
echo "        ',,::''.....,,,;;;;;;;;;;;;;;;;'''''';';;;'      "
sleep 0.1
echo "        :;:::''......,;;;;;;;;:::::;;;;'''''';;;;:       "
sleep 0.1
echo "        ;;;::,'.....,::;;::::::;;;;;;;;'''''';;,;;,      "
sleep 0.1
echo "        ;:;;:;'....,:::::::::::::::::;;;;'''':;,;;;      "
sleep 0.1
echo "        ';;;;;.,,,,::::::::::::::::::;;;;;''':::;;'      "
sleep 0.1
echo "        ;';;;;.;,,,,::::::::::::::::;;;;;;;''::;;;'      "
sleep 0.1
echo "        ;'';;:;..,,,;;;:;;:::;;;;;;;;;;;;;;;':::;;'      "
sleep 0.1
echo "        ;'';;;;;.,,;:;;;;;;;;;;;;;;;;;;;;;;;;;:;':;      "
sleep 0.1
echo "        ;''';;:;;.;;;;;;;;;;;;;;;;;;;;;;;;;;;''';:.      "
sleep 0.1
echo "        :';';;;;;;::,,,,,,,,,,,,,,:;;;;;;;;;;'''';       "
sleep 0.1
echo "         '';;;;:;;;.,,,,,,,,,,,,,,,,:;;;;;;;;'''''       "
sleep 0.1
echo "         '''';;;;;:..,,,,,,,,,,,,,,,,,;;;;;;;''':,       "
sleep 0.1
echo "         .'''';;;;....,,,,,,,,,,,,,,,,,,,:;;;''''        "
sleep 0.1
echo "          ''''';;;;....,,,,,,,,,,,,,,,,,,;;;''';.        "
sleep 0.1
echo "           '''';;;::.......,,,,,,,,,,,,,:;;;''''         "
sleep 0.1
echo "           '''';;;;:,......,,,,,,,,,,,,,;;;;;''          "
sleep 0.1
echo "            .'';;;;;:.....,,,,,,,,,,,,,,:;;;;'           "
sleep 0.1
echo "             ';;;;;:,....,,,,,,,,,,,,,,,:;;''            "
sleep 0.1
echo "               ;';;,,..,.,,,,,,,,,,,,,,,;;',             "
sleep 0.1
echo "                 '';:,,,,,,,,,,,,,,,::;;;:               "
sleep 0.1
echo "                  ':;'''''''''''''''';:.                 "
sleep 0.1
echo "                                                         "
sleep 0.1
echo " ,,,::::::::::::::::::::::::;;;;,::::::::::::::::::::::::"
sleep 0.1
echo " ,::::::::::::::::::::::::::;;;;,::::::::::::::::::::::::"
sleep 0.1
echo " ,:; ## ## ##  #####     ####      ## ## ##  ##   ##  ;::"
sleep 0.1
echo " ,,; ## ## ##  ## ##    ##         ## ## ##  ##   ##  ;::"
sleep 0.1
echo " ,,; ## ## ##  ##  ##  ##   ####   ## ## ##   ## ##   ;::"
sleep 0.1
echo " ,,' ## ## ##  ## ##    ##    ##   ## ## ##   ## ##   :::"
sleep 0.1
echo " ,:: ########  ####      ######    ########    ###    :::"
sleep 0.1
echo " ,,,:,,:,,:::,,,:;:::::::::::::::;;;:::;:;:::::::::::::::"
sleep 0.1
echo " ,,,,,,,,,,,,,,,,,,,,,,,,:,::::::;;;;:::::;;;;::::;;;;:::"
sleep 0.1
echo "                                                         "
sleep 0.3
echo "              (c) WDGWV. 2013, http://www.wdgwv.com             "
sleep 0.3
echo "          websites, Apps, Hosting, Services, Development.       "
sleep 0.4
echo ""
sleep 0.5
echo ""
sleep 0.4
echo ""
sleep 0.5
echo "* Please Wait While starting up!"
sleep 0.3
echo ""
sleep 0.3
echo ""
sleep 0.3
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo ""
clear
echo "WDGWV Setup Builder, Building setup..."
echo ""
cd $(dirname $0)
php $(dirname $0)/makeSetupfile.php
sleep 0.1
echo ""
sleep 0.1
echo ""
sleep 0.1
echo "Please wait while we shut down..."
sleep 10